### ISSUE TITLE
Don't join comand string and arguments by hand, let check_output do it for you.

### ISSUE THREAD

**Issue by Neppord** [Praqma/git-phlow-test#1]
https://github.com/Praqma/git-phlow-test/blob/ecb7f10ae2173b445a18a891a99194add198404e/src/cmd_wrapper.py#L4

I think its better to give check_output the list instead of giving it a string. If i remmeber correctly it is escaping arguments and other good stuff which we now loose.

If we still whant to keep this behaviure then we atleast should remove the duplication of joining.

**Comment by emilybache** [comment]
fixed in latest commit
